### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by Lunyyx** [bear-codes/Harbor#4]
All in the title. Thanks !

**Comment by RealTriassic** [comment]
> All in the title. Thanks !

Information is available in the project's README [right here](https://github.com/RealTriassic/Harbor#getting-started).
You need to grab the latest artifact from [here](https://github.com/RealTriassic/Harbor/actions) and run it. Currently we have wrappers for Python, Java (Kotlin) and Javascript (NodeJS), if you have any more questions, feel free to ask, otherwise, please close the issue.
